apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  name: workspace-llama-3-1-8b-instruct
resource:
  instanceType: "Standard_NC48ads_A100_v4"
  preferredNodes:
    - aks-gpunodepool-31608519-vmss000000
  labelSelector:
    matchLabels:
      kubernetes.azure.com/accelerator: nvidia
inference:
  preset:
    name: llama-3.1-8b-instruct
    accessMode: private
    presetOptions:
      modelAccessSecret: hf-token
