apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  name: workspace-llama-3-3-70b-instruct-blobfuse
resource:
  instanceType: "Standard_NC80adis_H100_v5"
  labelSelector:
    matchLabels:
      kubernetes.azure.com/accelerator: nvidia
inference:
  preset:
    name: "llama-3.3-70b-instruct"
    accessMode: download
    downloadOptions:
      env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hugging-face-hub-token
              key: HUGGING_FACE_HUB_TOKEN
      # volumeClaimTemplate:
      #   spec:
      #     storageClassName: azureblob-fuse-premium
      #     accessModes:
      #       - ReadWriteMany
      #     resources:
      #       requests:
      #         storage: 500Gi
