apiVersion: kaito.sh/v1alpha1
kind: Workspace
metadata:
  name: workspace-llama-3-3-70b-instruct
resource:
  instanceType: "Standard_NC96ads_A100_v4"
  count: 1
  labelSelector:
    matchLabels:
      kubernetes.azure.com/accelerator: nvidia
inference:
  preset:
    name: "llama-3.3-70b-instruct"
    accessMode: download
    downloadOptions:
      env:
        - name: HUGGING_FACE_HUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: hugging-face-hub-token
              key: HUGGING_FACE_HUB_TOKEN
      volumeClaimTemplate:
        spec:
          storageClassName: managed-premium
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 200Gi
