name: Check Fork PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  check-fork:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
          disable-sudo: true
          disable-telemetry: true
      - name: Check if PR is from fork
        run: |
          echo "PR head repository: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Base repository: ${{ github.event.pull_request.base.repo.full_name }}"
          echo "Is fork: ${{ github.event.pull_request.head.repo.fork }}"

          # Check if the PR is NOT from a fork
          if [ "${{ github.event.pull_request.head.repo.fork }}" == "false" ]; then
            echo "❌ Please create your PR from a fork of ${{ github.event.pull_request.base.repo.full_name }}. See https://github.com/kaito-project/kaito/issues/1301 for more information."
            exit 1
          else
            echo "✅ This PR is from a fork. Check passed."
          fi
